---
- name: Query all tenants
  cisco.aci.aci_tenant:
    host: "{{ ansible_host}}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: query
  delegate_to: localhost
  register: query_result
- name: Add a tenant
  cisco.aci.aci_tenant:
    host: "{{ ansible_host}}"
    username: "{{ username }}"
    password: "{{ password }}"
    tenant: demo-tennant-SW
    description: Workshop tenant with Ansible
    state: present
  delegate_to: localhost
